from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 554)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.LIDlabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LIDlabel.sizePolicy().hasHeightForWidth())
        self.LIDlabel.setSizePolicy(sizePolicy)
        self.LIDlabel.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.LIDlabel.setFont(font)
        self.LIDlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LIDlabel.setObjectName("LIDlabel")
        self.mainLayout.addWidget(self.LIDlabel, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setContentsMargins(-1, 15, -1, 10)
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem1)
        self.recordButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.recordButton.sizePolicy().hasHeightForWidth())
        self.recordButton.setSizePolicy(sizePolicy)
        self.recordButton.setMinimumSize(QtCore.QSize(200, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.recordButton.setFont(font)
        self.recordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recordButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.recordButton.setObjectName("recordButton")
        self.buttonsLayout.addWidget(self.recordButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem2)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setMinimumSize(QtCore.QSize(93, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.runButton.setFont(font)
        self.runButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.runButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.runButton.setObjectName("runButton")
        self.buttonsLayout.addWidget(self.runButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem3)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setMinimumSize(QtCore.QSize(93, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.stopButton.setObjectName("stopButton")
        self.buttonsLayout.addWidget(self.stopButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem4)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setMinimumSize(QtCore.QSize(93, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.saveButton.setObjectName("saveButton")
        self.buttonsLayout.addWidget(self.saveButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem5)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setMinimumSize(QtCore.QSize(93, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.clearButton.setFont(font)
        self.clearButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clearButton.setObjectName("clearButton")
        self.buttonsLayout.addWidget(self.clearButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem6)
        self.buttonsLayout.setStretch(0, 2)
        self.buttonsLayout.setStretch(1, 10)
        self.buttonsLayout.setStretch(2, 4)
        self.buttonsLayout.setStretch(3, 4)
        self.buttonsLayout.setStretch(4, 1)
        self.buttonsLayout.setStretch(5, 4)
        self.buttonsLayout.setStretch(6, 2)
        self.buttonsLayout.setStretch(7, 4)
        self.buttonsLayout.setStretch(8, 1)
        self.buttonsLayout.setStretch(9, 4)
        self.buttonsLayout.setStretch(10, 1)
        self.mainLayout.addLayout(self.buttonsLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem7)
        self.tabsLayout = QtWidgets.QHBoxLayout()
        self.tabsLayout.setContentsMargins(10, 10, 10, 10)
        self.tabsLayout.setObjectName("tabsLayout")
        self.filesTab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.filesTab.setFont(font)
        self.filesTab.setFocusPolicy(QtCore.Qt.NoFocus)
        self.filesTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.filesTab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.filesTab.setDocumentMode(True)
        self.filesTab.setObjectName("filesTab")
        self.tab1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab1.setFont(font)
        self.tab1.setObjectName("tab1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout.setObjectName("gridLayout")
        self.filesLayout = QtWidgets.QHBoxLayout()
        self.filesLayout.setObjectName("filesLayout")
        self.filesTable = QtWidgets.QTableWidget(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.filesTable.setFont(font)
        self.filesTable.setAlternatingRowColors(True)
        self.filesTable.setRowCount(0)
        self.filesTable.setObjectName("filesTable")
        self.filesTable.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.filesTable.setHorizontalHeaderItem(0, item)
        self.filesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.filesTable.horizontalHeader().setStretchLastSection(True)
        self.filesLayout.addWidget(self.filesTable)
        self.gridLayout.addLayout(self.filesLayout, 0, 0, 1, 1)
        self.clearfilesButton = QtWidgets.QPushButton(self.tab1)
        self.clearfilesButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.clearfilesButton.setFont(font)
        self.clearfilesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearfilesButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clearfilesButton.setObjectName("clearfilesButton")
        self.gridLayout.addWidget(self.clearfilesButton, 1, 0, 1, 1)
        self.filesTab.addTab(self.tab1, "")
        self.tabsLayout.addWidget(self.filesTab)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tabsLayout.addItem(spacerItem8)
        self.resultTab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.resultTab.setFont(font)
        self.resultTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.resultTab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.resultTab.setDocumentMode(True)
        self.resultTab.setObjectName("resultTab")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resultLayout = QtWidgets.QHBoxLayout()
        self.resultLayout.setObjectName("resultLayout")
        self.resultTable = QtWidgets.QTableWidget(self.tab2)
        self.resultTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.resultTable.setAlternatingRowColors(True)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(3)
        self.resultTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(2, item)
        self.resultTable.horizontalHeader().setCascadingSectionResizes(True)
        self.resultTable.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.resultTable.horizontalHeader().setMinimumSectionSize(50)
        self.resultTable.horizontalHeader().setSortIndicatorShown(False)
        self.resultTable.verticalHeader().setCascadingSectionResizes(True)
        self.resultTable.verticalHeader().setDefaultSectionSize(30)
        self.resultLayout.addWidget(self.resultTable)
        self.gridLayout_2.addLayout(self.resultLayout, 0, 0, 1, 1)
        self.resultTab.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.resultLayout2 = QtWidgets.QHBoxLayout()
        self.resultLayout2.setObjectName("resultLayout2")
        self.resultTable2 = QtWidgets.QTableWidget(self.tab3)
        self.resultTable2.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.resultTable2.setAlternatingRowColors(True)
        self.resultTable2.setRowCount(0)
        self.resultTable2.setObjectName("resultTable2")
        self.resultTable2.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable2.setHorizontalHeaderItem(4, item)
        self.resultLayout2.addWidget(self.resultTable2)
        self.gridLayout_3.addLayout(self.resultLayout2, 0, 0, 1, 1)
        self.resultTab.addTab(self.tab3, "")
        self.tabsLayout.addWidget(self.resultTab)
        self.tabsLayout.setStretch(0, 2)
        self.tabsLayout.setStretch(2, 3)
        self.mainLayout.addLayout(self.tabsLayout)
        self.mainLayout.setStretch(0, 2)
        self.mainLayout.setStretch(1, 1)
        self.mainLayout.setStretch(2, 2)
        self.mainLayout.setStretch(3, 1)
        self.mainLayout.setStretch(4, 18)
        self.verticalLayout.addLayout(self.mainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHistory = QtWidgets.QMenu(self.menubar)
        self.menuHistory.setObjectName("menuHistory")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHistory.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.filesTab.setCurrentIndex(0)
        self.resultTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LIDlabel.setText(_translate("MainWindow", "LANGUAGE IDENTIFIER"))
        self.recordButton.setText(_translate("MainWindow", "Live Record"))
        self.runButton.setText(_translate("MainWindow", "RUN"))
        self.stopButton.setText(_translate("MainWindow", "STOP"))
        self.saveButton.setText(_translate("MainWindow", "SAVE"))
        self.clearButton.setText(_translate("MainWindow", "CLEAR"))
        item = self.filesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File"))
        self.clearfilesButton.setText(_translate("MainWindow", "Clear Selected Files"))
        self.filesTab.setTabText(self.filesTab.indexOf(self.tab1), _translate("MainWindow", "SELECTED FILES"))
        item = self.resultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File"))
        item = self.resultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Language"))
        item = self.resultTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Confidence"))
        self.resultTab.setTabText(self.resultTab.indexOf(self.tab2), _translate("MainWindow", "RESULTS"))
        item = self.resultTable2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File"))
        item = self.resultTable2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Language1"))
        item = self.resultTable2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Confidence1"))
        item = self.resultTable2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Language2"))
        item = self.resultTable2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Confidence2"))
        self.resultTab.setTabText(self.resultTab.indexOf(self.tab3), _translate("MainWindow", "DETAILS"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHistory.setTitle(_translate("MainWindow", "History"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder"))
