# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 211, 351))
        self.frame.setStyleSheet("COLOR=rgb(170, 85, 255)\n"
"GRADIENT=qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147))")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.result_view = QtWidgets.QLineEdit(self.frame)
        self.result_view.setGeometry(QtCore.QRect(10, 20, 191, 61))
        self.result_view.setStyleSheet("COLOR=rgb(255, 255, 255)")
        self.result_view.setObjectName("result_view")
        self.clear_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("C"))
        self.clear_button.setGeometry(QtCore.QRect(11, 91, 41, 41))
        self.clear_button.setStyleSheet("COLOR=rgb(131, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.clear_button.setIconSize(QtCore.QSize(10, 10))
        self.clear_button.setAutoDefault(True)
        self.clear_button.setDefault(True)
        self.clear_button.setFlat(False)
        self.clear_button.setObjectName("clear_button")
        self.back_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.remove_it())
        self.back_button.setGeometry(QtCore.QRect(60, 90, 41, 41))
        self.back_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.back_button.setIconSize(QtCore.QSize(10, 10))
        self.back_button.setAutoDefault(True)
        self.back_button.setDefault(True)
        self.back_button.setFlat(False)
        self.back_button.setObjectName("back_button")
        self.percent_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("%"))
        self.percent_button.setGeometry(QtCore.QRect(110, 90, 41, 41))
        self.percent_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.percent_button.setIconSize(QtCore.QSize(10, 10))
        self.percent_button.setAutoDefault(True)
        self.percent_button.setDefault(True)
        self.percent_button.setFlat(False)
        self.percent_button.setObjectName("percent_button")
        self.seven_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("7"))
        self.seven_button.setGeometry(QtCore.QRect(10, 140, 41, 41))
        self.seven_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.seven_button.setIconSize(QtCore.QSize(10, 10))
        self.seven_button.setAutoDefault(True)
        self.seven_button.setDefault(True)
        self.seven_button.setFlat(False)
        self.seven_button.setObjectName("seven_button")
        self.divide_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("/"))
        self.divide_button.setGeometry(QtCore.QRect(160, 90, 41, 41))
        self.divide_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.divide_button.setIconSize(QtCore.QSize(10, 10))
        self.divide_button.setAutoDefault(True)
        self.divide_button.setDefault(True)
        self.divide_button.setFlat(False)
        self.divide_button.setObjectName("divide_button")
        self.four_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("4"))
        self.four_button.setGeometry(QtCore.QRect(10, 190, 41, 41))
        self.four_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.four_button.setIconSize(QtCore.QSize(10, 10))
        self.four_button.setAutoDefault(True)
        self.four_button.setDefault(True)
        self.four_button.setFlat(False)
        self.four_button.setObjectName("four_button")
        self.product_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("*"))
        self.product_button.setGeometry(QtCore.QRect(160, 140, 41, 41))
        self.product_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.product_button.setIconSize(QtCore.QSize(10, 10))
        self.product_button.setAutoDefault(True)
        self.product_button.setDefault(True)
        self.product_button.setFlat(False)
        self.product_button.setObjectName("product_button")
        self.eight_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("8"))
        self.eight_button.setGeometry(QtCore.QRect(60, 140, 41, 41))
        self.eight_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.eight_button.setIconSize(QtCore.QSize(10, 10))
        self.eight_button.setAutoDefault(True)
        self.eight_button.setDefault(True)
        self.eight_button.setFlat(False)
        self.eight_button.setObjectName("eight_button")
        self.nine_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("9"))
        self.nine_button.setGeometry(QtCore.QRect(110, 140, 41, 41))
        self.nine_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.nine_button.setIconSize(QtCore.QSize(10, 10))
        self.nine_button.setAutoDefault(True)
        self.nine_button.setDefault(True)
        self.nine_button.setFlat(False)
        self.nine_button.setObjectName("nine_button")
        self.five_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("5"))
        self.five_button.setGeometry(QtCore.QRect(60, 190, 41, 41))
        self.five_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.five_button.setIconSize(QtCore.QSize(10, 10))
        self.five_button.setAutoDefault(True)
        self.five_button.setDefault(True)
        self.five_button.setFlat(False)
        self.five_button.setObjectName("five_button")
        self.six_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("6"))
        self.six_button.setGeometry(QtCore.QRect(110, 190, 41, 41))
        self.six_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.six_button.setIconSize(QtCore.QSize(10, 10))
        self.six_button.setAutoDefault(True)
        self.six_button.setDefault(True)
        self.six_button.setFlat(False)
        self.six_button.setObjectName("six_button")
        self.two_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("2"))
        self.two_button.setGeometry(QtCore.QRect(60, 240, 41, 41))
        self.two_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.two_button.setIconSize(QtCore.QSize(10, 10))
        self.two_button.setAutoDefault(True)
        self.two_button.setDefault(True)
        self.two_button.setFlat(False)
        self.two_button.setObjectName("two_button")
        self.three_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("3"))
        self.three_button.setGeometry(QtCore.QRect(110, 240, 41, 41))
        self.three_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.three_button.setIconSize(QtCore.QSize(10, 10))
        self.three_button.setAutoDefault(True)
        self.three_button.setDefault(True)
        self.three_button.setFlat(False)
        self.three_button.setObjectName("three_button")
        self.zero_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("0"))
        self.zero_button.setGeometry(QtCore.QRect(60, 290, 41, 41))
        self.zero_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.zero_button.setIconSize(QtCore.QSize(10, 10))
        self.zero_button.setAutoDefault(True)
        self.zero_button.setDefault(True)
        self.zero_button.setFlat(False)
        self.zero_button.setObjectName("zero_button")
        self.sub_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("-"))
        self.sub_button.setGeometry(QtCore.QRect(160, 190, 41, 41))
        self.sub_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.sub_button.setIconSize(QtCore.QSize(10, 10))
        self.sub_button.setAutoDefault(True)
        self.sub_button.setDefault(True)
        self.sub_button.setFlat(False)
        self.sub_button.setObjectName("sub_button")
        self.point_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.dot_it())
        self.point_button.setGeometry(QtCore.QRect(110, 290, 41, 41))
        self.point_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.point_button.setIconSize(QtCore.QSize(10, 10))
        self.point_button.setAutoDefault(True)
        self.point_button.setDefault(True)
        self.point_button.setFlat(False)
        self.point_button.setObjectName("point_button")
        self.add_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("+"))
        self.add_button.setGeometry(QtCore.QRect(160, 240, 41, 41))
        self.add_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.add_button.setIconSize(QtCore.QSize(10, 10))
        self.add_button.setAutoDefault(True)
        self.add_button.setDefault(True)
        self.add_button.setFlat(False)
        self.add_button.setObjectName("add_button")
        self.answer_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.math_it())
        self.answer_button.setGeometry(QtCore.QRect(160, 290, 41, 41))
        self.answer_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.answer_button.setIconSize(QtCore.QSize(10, 10))
        self.answer_button.setAutoDefault(True)
        self.answer_button.setDefault(True)
        self.answer_button.setFlat(False)
        self.answer_button.setObjectName("answer_button")
        self.one_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("1"))
        self.one_button.setGeometry(QtCore.QRect(10, 240, 41, 41))
        self.one_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.one_button.setIconSize(QtCore.QSize(10, 10))
        self.one_button.setAutoDefault(True)
        self.one_button.setDefault(True)
        self.one_button.setFlat(False)
        self.one_button.setObjectName("one_button")
        self.power_button = QtWidgets.QPushButton(self.frame,clicked=lambda:self.press_it("**"))
        self.power_button.setGeometry(QtCore.QRect(10, 290, 41, 41))
        self.power_button.setStyleSheet("COLOR=rgb(141, 131, 200)\n"
"GRADIENT=qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.power_button.setIconSize(QtCore.QSize(10, 10))
        self.power_button.setAutoDefault(True)
        self.power_button.setDefault(True)
        self.power_button.setFlat(False)
        self.power_button.setObjectName("power_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def math_it(self):
        screen=self.result_view.text()
        try:
            if screen[-1]=='%':
                answer=self.percent_it(screen)
                self.result_view.setText(answer)
            else:
                answer=eval(screen)
                self.result_view.setText(str(answer))
        except:
            self.result_view.setText('Error')
    def percent_it(self,screen):
        x=screen[:-1]
        ans=int(x)/100
        return str(ans)
    
    def remove_it(self):
        screen=self.result_view.text()
        screen=screen[:-1]
        self.result_view.setText(screen)
    def check_point(self,screen):
        h=screen[-1]
        s=""
        for i in screen:
            if not i.isdigit():
                s=i
        if s==".":
            return True
        return False
    def dot_it(self):
        screen =self.result_view.text()
        if screen[-1] == "." or self.check_point(screen):
            pass
        else:
            self.result_view.setText(f'{screen}.')
    def press_it(self,pressed):
        if pressed=="C":
            self.result_view.setText("0")
        else:
            if self.result_view.text()=="0":
                self.result_view.setText("")
                
            self.result_view.setText(f'{self.result_view.text()}{pressed}')
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.back_button.setText(_translate("MainWindow", "<-"))
        self.percent_button.setText(_translate("MainWindow", "%"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.divide_button.setText(_translate("MainWindow", "/"))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.product_button.setText(_translate("MainWindow", "*"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.two_button.setText(_translate("MainWindow", "2"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.zero_button.setText(_translate("MainWindow", "0"))
        self.sub_button.setText(_translate("MainWindow", "-"))
        self.point_button.setText(_translate("MainWindow", "."))
        self.add_button.setText(_translate("MainWindow", "+"))
        self.answer_button.setText(_translate("MainWindow", "="))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.power_button.setText(_translate("MainWindow", "**"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
